// Product Data
const products = [
    // Electronics
    {
        id: 1,
        name: "iPhone 15 Pro Max",
        brand: "Apple",
        category: "electronics",
        price: 159900,
        originalPrice: 179900,
        discount: 11,
        rating: 4.7,
        ratingCount: 2456,
        image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=300&h=300&fit=crop",
        description: "Experience the ultimate smartphone with A17 Pro chip, titanium design, and advanced camera system.",
        delivery: "Free Delivery by Tomorrow",
        inStock: true
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra",
        brand: "Samsung",
        category: "electronics",
        price: 129999,
        originalPrice: 149999,
        discount: 13,
        rating: 4.6,
        ratingCount: 1823,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=300&h=300&fit=crop",
        description: "Galaxy AI is here. Search like never before, translate calls live, and format notes in a tap.",
        delivery: "Free Delivery by Tomorrow",
        inStock: true
    },
    {
        id: 3,
        name: "Sony WH-1000XM5 Headphones",
        brand: "Sony",
        category: "electronics",
        price: 26990,
        originalPrice: 34990,
        discount: 23,
        rating: 4.8,
        ratingCount: 3421,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop",
        description: "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling.",
        delivery: "Free Delivery in 2 days",
        inStock: true
    },
    {
        id: 4,
        name: "MacBook Pro 16-inch M3",
        brand: "Apple",
        category: "electronics",
        price: 249900,
        originalPrice: 269900,
        discount: 7,
        rating: 4.9,
        ratingCount: 876,
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&h=300&fit=crop",
        description: "Supercharged by M3 Pro or M3 Max chip. Up to 22 hours of battery life.",
        delivery: "Free Delivery by Tomorrow",
        inStock: true
    },
    {
        id: 5,
        name: "iPad Pro 12.9-inch",
        brand: "Apple",
        category: "electronics",
        price: 109900,
        originalPrice: 119900,
        discount: 8,
        rating: 4.7,
        ratingCount: 1234,
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=300&h=300&fit=crop",
        description: "The ultimate iPad experience with M2 chip, Liquid Retina XDR display, and all-day battery life.",
        delivery: "Free Delivery in 2 days",
        inStock: true
    },
    // Fashion
    {
        id: 6,
        name: "Nike Air Max 270",
        brand: "Nike",
        category: "fashion",
        price: 12995,
        originalPrice: 15995,
        discount: 19,
        rating: 4.5,
        ratingCount: 2341,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop",
        description: "The Nike Air Max 270 delivers visible cushioning under every step with sleek, running-inspired design.",
        delivery: "Free Delivery in 3 days",
        inStock: true
    },
    {
        id: 7,
        name: "Adidas Ultraboost 23",
        brand: "Adidas",
        category: "fashion",
        price: 16999,
        originalPrice: 19999,
        discount: 15,
        rating: 4.6,
        ratingCount: 1876,
        image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=300&h=300&fit=crop",
        description: "Experience incredible energy return with the Ultraboost 23. Perfect for running and everyday wear.",
        delivery: "Free Delivery in 3 days",
        inStock: true
    },
    {
        id: 8,
        name: "Levi's 501 Original Jeans",
        brand: "Levi's",
        category: "fashion",
        price: 2999,
        originalPrice: 4999,
        discount: 40,
        rating: 4.4,
        ratingCount: 5678,
        image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=300&h=300&fit=crop",
        description: "The original blue jean since 1873. The 501 Original Fit Jeans are the blueprint for all jeans to follow.",
        delivery: "Free Delivery in 4 days",
        inStock: true
    },
    {
        id: 9,
        name: "Ray-Ban Aviator Sunglasses",
        brand: "Ray-Ban",
        category: "fashion",
        price: 8990,
        originalPrice: 11990,
        discount: 25,
        rating: 4.7,
        ratingCount: 3456,
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=300&h=300&fit=crop",
        description: "The Original Aviator. Classic pilot shape with lightweight metal frame and crystal lenses.",
        delivery: "Free Delivery in 2 days",
        inStock: true
    },
    {
        id: 10,
        name: "Tommy Hilfiger Polo Shirt",
        brand: "Tommy Hilfiger",
        category: "fashion",
        price: 2499,
        originalPrice: 3999,
        discount: 38,
        rating: 4.3,
        ratingCount: 2134,
        image: "https://images.unsplash.com/photo-1625910513413-5fc45e80b573?w=300&h=300&fit=crop",
        description: "Classic fit polo shirt with signature Tommy Hilfiger branding. 100% cotton for comfort.",
        delivery: "Free Delivery in 3 days",
        inStock: true
    },
    // Home & Furniture
    {
        id: 11,
        name: "Premium Sofa Set (3+1+1)",
        brand: "HomeTown",
        category: "home",
        price: 45999,
        originalPrice: 79999,
        discount: 43,
        rating: 4.2,
        ratingCount: 567,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&h=300&fit=crop",
        description: "Luxurious 5-seater sofa set with premium fabric upholstery and solid wood frame.",
        delivery: "Free Delivery in 7 days",
        inStock: true
    },
    {
        id: 12,
        name: "Wooden Dining Table Set (6 Seater)",
        brand: "Durian",
        category: "home",
        price: 34999,
        originalPrice: 54999,
        discount: 36,
        rating: 4.4,
        ratingCount: 892,
        image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=300&h=300&fit=crop",
        description: "Elegant 6-seater dining table set made from premium Sheesham wood with natural finish.",
        delivery: "Free Delivery in 7 days",
        inStock: true
    },
    {
        id: 13,
        name: "King Size Bed with Storage",
        brand: "Wakefit",
        category: "home",
        price: 28999,
        originalPrice: 45999,
        discount: 37,
        rating: 4.5,
        ratingCount: 2341,
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=300&h=300&fit=crop",
        description: "Solid wood king size bed with hydraulic storage. Includes mattress support.",
        delivery: "Free Delivery in 5 days",
        inStock: true
    },
    {
        id: 14,
        name: "Decorative Wall Art Set",
        brand: "ExclusiveLane",
        category: "home",
        price: 3999,
        originalPrice: 6999,
        discount: 43,
        rating: 4.6,
        ratingCount: 1234,
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=300&h=300&fit=crop",
        description: "Set of 3 canvas wall art prints. Perfect for living room or bedroom decor.",
        delivery: "Free Delivery in 3 days",
        inStock: true
    },
    {
        id: 15,
        name: "Memory Foam Mattress (Queen)",
        brand: "Sunday",
        category: "home",
        price: 19999,
        originalPrice: 34999,
        discount: 43,
        rating: 4.7,
        ratingCount: 3456,
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=300&h=300&fit=crop",
        description: "Orthopedic memory foam mattress with 100-night trial and 10-year warranty.",
        delivery: "Free Delivery in 4 days",
        inStock: true
    },
    // Appliances
    {
        id: 16,
        name: "LG 55-inch 4K OLED TV",
        brand: "LG",
        category: "appliances",
        price: 129990,
        originalPrice: 179990,
        discount: 28,
        rating: 4.8,
        ratingCount: 1234,
        image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=300&h=300&fit=crop",
        description: "Perfect blacks and infinite contrast with self-lit OLED technology. Dolby Vision IQ & Dolby Atmos.",
        delivery: "Free Installation & Delivery",
        inStock: true
    },
    {
        id: 17,
        name: "Samsung Side-by-Side Refrigerator",
        brand: "Samsung",
        category: "appliances",
        price: 74990,
        originalPrice: 99990,
        discount: 25,
        rating: 4.5,
        ratingCount: 2345,
        image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=300&h=300&fit=crop",
        description: "653L capacity with Twin Cooling Plus technology. Digital inverter compressor.",
        delivery: "Free Installation & Delivery",
        inStock: true
    },
    {
        id: 18,
        name: "IFB Front Load Washing Machine",
        brand: "IFB",
        category: "appliances",
        price: 38990,
        originalPrice: 49990,
        discount: 22,
        rating: 4.4,
        ratingCount: 3456,
        image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=300&h=300&fit=crop",
        description: "8 kg fully automatic front loading washing machine with steam wash technology.",
        delivery: "Free Installation & Delivery",
        inStock: true
    },
    {
        id: 19,
        name: "Daikin Split Air Conditioner 1.5 Ton",
        brand: "Daikin",
        category: "appliances",
        price: 42990,
        originalPrice: 56990,
        discount: 25,
        rating: 4.6,
        ratingCount: 1876,
        image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=300&h=300&fit=crop",
        description: "5 Star inverter split AC with copper condenser. PM 2.5 filter and Coanda airflow.",
        delivery: "Free Installation & Delivery",
        inStock: true
    },
    {
        id: 20,
        name: "Philips Air Fryer HD9252",
        brand: "Philips",
        category: "appliances",
        price: 8999,
        originalPrice: 14995,
        discount: 40,
        rating: 4.5,
        ratingCount: 5678,
        image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=300&h=300&fit=crop",
        description: "Rapid Air technology for healthier frying. 4.1L capacity with digital display.",
        delivery: "Free Delivery in 2 days",
        inStock: true
    },
    // Toys & Baby
    {
        id: 21,
        name: "LEGO Star Wars Millennium Falcon",
        brand: "LEGO",
        category: "toys",
        price: 14999,
        originalPrice: 18999,
        discount: 21,
        rating: 4.9,
        ratingCount: 876,
        image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=300&h=300&fit=crop",
        description: "Build and display the iconic Millennium Falcon. 1351 pieces with 6 minifigures.",
        delivery: "Free Delivery in 3 days",
        inStock: true
    },
    {
        id: 22,
        name: "Barbie Dreamhouse",
        brand: "Mattel",
        category: "toys",
        price: 12999,
        originalPrice: 16999,
        discount: 24,
        rating: 4.7,
        ratingCount: 2345,
        image: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=300&h=300&fit=crop",
        description: "3-story Dreamhouse with 75+ accessories. Includes lights and sounds.",
        delivery: "Free Delivery in 3 days",
        inStock: true
    },
    {
        id: 23,
        name: "Hot Wheels Track Set",
        brand: "Hot Wheels",
        category: "toys",
        price: 2999,
        originalPrice: 4999,
        discount: 40,
        rating: 4.4,
        ratingCount: 3456,
        image: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=300&h=300&fit=crop",
        description: "Ultimate garage playset with motorized track and 4 die-cast cars included.",
        delivery: "Free Delivery in 2 days",
        inStock: true
    },
    {
        id: 24,
        name: "Baby Stroller Premium",
        brand: "Chicco",
        category: "toys",
        price: 15999,
        originalPrice: 22999,
        discount: 30,
        rating: 4.6,
        ratingCount: 1234,
        image: "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=300&h=300&fit=crop",
        description: "Lightweight stroller with 5-point harness, canopy, and easy fold mechanism.",
        delivery: "Free Delivery in 4 days",
        inStock: true
    },
    {
        id: 25,
        name: "Remote Control Car - Off Road",
        brand: "Toyzone",
        category: "toys",
        price: 1999,
        originalPrice: 3999,
        discount: 50,
        rating: 4.3,
        ratingCount: 4567,
        image: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=300&h=300&fit=crop",
        description: "High-speed off-road RC car with 4WD and rechargeable battery. 2.4GHz remote.",
        delivery: "Free Delivery in 2 days",
        inStock: true
    },
    // Grocery
    {
        id: 26,
        name: "Organic Basmati Rice (5kg)",
        brand: "India Gate",
        category: "grocery",
        price: 699,
        originalPrice: 899,
        discount: 22,
        rating: 4.5,
        ratingCount: 8765,
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop",
        description: "Premium organic basmati rice. Aged for perfect aroma and taste.",
        delivery: "Free Delivery Today",
        inStock: true
    },
    {
        id: 27,
        name: "Extra Virgin Olive Oil (1L)",
        brand: "Figaro",
        category: "grocery",
        price: 599,
        originalPrice: 799,
        discount: 25,
        rating: 4.6,
        ratingCount: 4567,
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&h=300&fit=crop",
        description: "100% pure extra virgin olive oil. Cold pressed for maximum nutrition.",
        delivery: "Free Delivery Today",
        inStock: true
    },
    {
        id: 28,
        name: "Green Tea Bags (100 count)",
        brand: "Twinings",
        category: "grocery",
        price: 449,
        originalPrice: 599,
        discount: 25,
        rating: 4.4,
        ratingCount: 3456,
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=300&h=300&fit=crop",
        description: "Pure green tea with antioxidants. Individually wrapped tea bags.",
        delivery: "Free Delivery Today",
        inStock: true
    },
    {
        id: 29,
        name: "Almonds Premium (500g)",
        brand: "Happilo",
        category: "grocery",
        price: 549,
        originalPrice: 749,
        discount: 27,
        rating: 4.7,
        ratingCount: 2345,
        image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=300&h=300&fit=crop",
        description: "Premium California almonds. Rich in protein and healthy fats.",
        delivery: "Free Delivery Today",
        inStock: true
    },
    {
        id: 30,
        name: "Organic Honey (500g)",
        brand: "Dabur",
        category: "grocery",
        price: 299,
        originalPrice: 399,
        discount: 25,
        rating: 4.5,
        ratingCount: 5678,
        image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=300&h=300&fit=crop",
        description: "100% pure and organic honey. No added sugar or preservatives.",
        delivery: "Free Delivery Today",
        inStock: true
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = products;
}